variables:
  global_variable: value  # this is a global available to all stages and jobs

stages:
- stage: Build
  variables:
    stage_variable1: value3 # available in Build stage and all jobs
  jobs:
  - job: BuildJob
    variables:
      job_variable1: value1    # this is only available in BuildJob
    steps:
    - bash: echo $(stage_variable1) ## works
    - bash: echo $(global_variable) ## works
    - bash: echo $(job_variable1) ## works